### ISSUE TITLE
metadata is missing and issue with --trim

### ISSUE THREAD

**Issue by areensh** [arosenfeld/immunedb#93]
Hi,

when i run immunedb_import i get the error metadata file not found though it is there! 
also it doesn't accept the --trim parameters.
 attached a screenshot of the commands i was running.
![Screenshot from 2021-01-19 17-10-32](https://user-images.githubusercontent.com/34010176/105053211-5f384d00-5a79-11eb-8c14-e0585c6fa6b7.png)

**Comment by arosenfeld** [comment]
After the `immunedb_import` command the first argument needs to be the path to your `db_config` file.  After that you can specify the `airr` format, germlines, sample directory, and then any additional flags such as `--trim-to`.

For example:

`immunedb_import config.json airr v_germlines.fasta j_germlines.fasta /path/to/samples --trim-to 80`

You can also list all the other optional flags by passing `--help`.  Due to how Python parses arguments, you'll need to do this _after_ the config and airr flags, e.g.:

`immunedb_import /path/to/config.json airr --help`

Let me know if this doesn't work and I can look into it more!

Best,
Aaron

**Comment by areensh** [comment]
yes i followed the documentation, i created a metadata file with` immunedb_metadata --use-filenames ` and then i edited the file and save it and i can see it is inside the share/input directory but still getting not found!

**Comment by arosenfeld** [comment]
For the time being, I'd recommend passing the `--metadata PATH_TO_METADATA` flag where you can directly specify it's path.

It is odd that the file can't be found, though. Perhaps remove all the backslashes from the command?  It may be interpreting the sample directory as `[SPACE]/share/input` rather than `/share/input`

**Comment by areensh** [comment]
yes it is very odd! 
i have double checked the command , it doesnt seem to have any extra spaces!

`immunedb_import /share/configs/dbname.json airr \ /root/germlines/igblast/human/IGHV.gapped.fasta \ /root/germlines/igblast/human/IGHJ.gapped.fasta \ /share/input --trim-to 80`

i didnt run the metdata with path again still didnt work `immunedb_metadata --path /share/input --use-filenames`

any changes have been done to the immunedb_import command?

**Comment by areensh** [comment]
ok so i restarted the docker image again and it worked!!

thanks anyway

**Comment by arosenfeld** [comment]
Great, glad it's working!  I'm going to close the issue for now but feel free to re-open it if you have any other issues with this.
